sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install -U tox codecov tox-travis
before_script:
  - python -c "import manpki.config; manpki.config.setup()"
script:
  - tox
after_success:
- codecov
