#! /bin/bash
### BEGIN INIT INFO
# Provides:          manpki
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The main manpki process
# Description:       Main daemon process for ManPKI
#
### END INIT INFO
#
# Author:       Gaetan Ferez <gaetan@ferez.fr>
#
APPNAME=manpki
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
DAEMON=/usr/local/bin/manpkid
DAEMON_USER=manpki
DAEMON_OPTS="-d"
PIDFILE=/var/run/manpki/manpkid.pid
LOGFILE=/var/log/$DAEMON.log


. /lib/lsb/init-functions


if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi


case "$1" in
  start)
        log_daemon_msg "Starting $APPNAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --exec $DAEMON -- $DAEMON_OPTS
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping $APPNAME daemon"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
